const MIN_LIKES = 15;
const MAX_LIKES = 200;
const AVATAR_MIN_INDEX = 1;
const AVATAR_MAX_INDEX = 6;
const MIN_NUMBER_COMMENTS = 2;
const MAX_NUMBER_COMMENTS = 15;
const MAX_GENERATED_OBJECTS = 25;
const COMMENTS_STEP = 5;
const SCALE_STEP = 0.25;
const SCALE_DEFAULT = 0.5;
const MAX_SCALE = 1;
const MIN_SCALE = 0.25;
const VALID_SYMBOLS = /^#[a-zа-яё0-9]{0,19}$/i;
const VALID_FIRST_SYMBOL = /^#/;
const MAX_HASHTAGS = 5;

export {
  MIN_LIKES,
  MAX_LIKES,
  AVATAR_MIN_INDEX,
  AVATAR_MAX_INDEX,
  MIN_NUMBER_COMMENTS,
  MAX_NUMBER_COMMENTS,
  MAX_GENERATED_OBJECTS,
  COMMENTS_STEP,
  SCALE_STEP,
  SCALE_DEFAULT,
  MAX_SCALE,
  MIN_SCALE,
  VALID_SYMBOLS,
  VALID_FIRST_SYMBOL,
  MAX_HASHTAGS
};
